export const skillsToInclude = [
  "Teamwork (4+ years)",
  // eslint-disable-next-line no-script-url
  "JavaScript: ES6+ (8+ months)",
  "REST API (6+ months)",
  "Fetch API (6+ months)",
  "Axios (6+ months)",
  "TypeScript (2+ months)",
  "HTML5 & CSS3 (1+ year)",
  "Styled Components (6+ months)",
  "Semantic & accessible HTML (1+ year)",
  "BEM convention (1+ year)",
  "Bootstrap (crash course)",
  "SASS (crash course)",
  "Tailwind CSS (1+ month)",
  "React (6+ months)",
  "React Hooks (6+ months)",
  "React Router (6+ months)",
  "Ract Context (2 months)",
  "Immutability (6+ months)",
  "Redux (Toolkit) (5+ months)",
  "Redux-Saga (5+ months)",
  "React Query (2+ months, movies-browser-ts-rq)",
  "Next.js: appDir (1 month, my-website)",
  "MongoDB (1 month)",
  "Prisma (crash course)",
  "Node.js (crash course, tracalorieapp)",
  "Express.js (crash course, tracalorieapp)",
  "Git (8+ months)",
  "GitHub Pull Requests & Review (6+ months)",
  "Trello (movie-browser project)",
  "Scrum (movie-browser project)",
  "Figma (movie-browser, personal-homepage)",
  "Design in Figma (crash course)",
  "Canva (2+ months)",
  "OOP (tracalorieapp, C++ at university 2 semesters)",
];
