export const skillsToInclude = [
  // eslint-disable-next-line no-script-url
  "JavaScript: ES6+",
  "TypeScript",
  "React",
  "Working with API (fetch, axios)",
  "React Hooks",
  "React Router",
  "Redux",
  "Redux (Toolkit)",
  "Redux-Saga",
  "NPM",
  "Immutability",
  "Teamwork",
  "GitHub Pull Requests & Review",
  "Trello",
  "Scrum",
  "Git",
  "Promises, Async/Await",
  "Error handling",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "CSS Flexbox",
  "CSS Grid",
  "CSS BEM convention",
  "Markdown",
  "Styled Components",
  "React Query",
];
