export const skillsToInclude = [
  "Teamwork (4+ years, university, work, projects)",
  "HTML5 & CSS3 (1+ year)",
  "Semantic & accessible HTML (1+ year)",
  "BEM convention (1+ year)",
  // eslint-disable-next-line no-script-url
  "JavaScript: ES6+ (8+ months)",
  "Git (8+ months)",
  "GitHub Pull Requests & Review (6+ months)",
  "NPM (6+ months)",
  "REST API Fetch, Axios(6+ months)",
  "Styled Components (6+ months)",
  "React (6+ months)",
  "React Hooks (6+ months)",
  "React Router (6+ months)",
  "Immutability (6+ months)",
  "Redux (Toolkit) (6+ months)",
  "Redux-Saga (6+ months)",
  "Ract Context (2+ months)",
  "React Query (2+ months, movies-browser-ts-rq)",
  "TypeScript (2+ months)",
  "Canva (2+ months)",
  "Tailwind CSS (1+ month)",
  "Next.js: appDir (1 month, arbnb-clone)",
  "MongoDB (1 month)",
];
